server:
  port: 9090

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-micro-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/AuthDB
    username: postgres
    password: burhan71
  jpa:
    hibernate:
      ddl-auto: create

bu-benim-tanimim:
  userprofile-url: http://localhost:9093/api/v1/user
  bunedirki: "buraya bir şeyler yazabilirsiniz."